sudo: required
services:
  - docker

before_install:
  - docker build -t ankur/docker-react -f Dockerfile.Dev .

script:
  #  - docker run ankur/docker-react npm run test -- --coverage
  - docker run -e CI=true ankur/docker-react npm run test