sudo: required
services:
  - docker

before_install:
  - docker build -t docker-react -f Dockerfile.dev .

script:
  #  - docker run ankur/docker-react npm run test -- --coverage
  - docker run -e CI=true docker-react npm run test


deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker-daniel"
  env: "Docker-daniel-env"
  bucket_name: "elasticbeanstalk-eu-north-1-557498678765"
  bucket_path: "docker-daniel"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"